<?php
$title = $this->getTitle();
if($title) {
    $this->setTitle($title." :: ".$this->t->translate('Change password'));
} else {
    $this->setTitle($this->t->translate('Change password'));
}
?><div class="page-header">
        <h2><?= $this->t->translate('Change password'); ?></h2>
        </div>
<?php if(isset($this->showAlert)): ?>
        <div class="message-info-alert">
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Error:</span>
                <?= $this->t->translate($this->showAlert);?>
            </div>
        </div>
<?php endif; ?>
<?php if(isset($this->isSave)): ?>
        <div class="message-info-alert response-alert">
            <div class="alert alert-success">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                <span class="message"><?= $this->t->translate('The data is stored'); ?>!</span>
            </div>
        </div>
<?php endif;?>
        <form id="change-password-user-form" role="form" action="<?= $this->router->createPath('account_change_password'); ?>" method="POST" novalidate>
            <div class="control-group">
                <!-- Password-->
                <label class="control-label" for="old_password"><?= $this->t->translate('Old password'); ?></label>
                <div class="controls">
                    <input type="password" class="form-control" id="old_password" name="old_password" minlength="6" data-validation-minlength-message="<?= $this->t->translate('Too short: Minimum of \'6\' characters'); ?>" data-validation-required-message="<?= $this->t->translate('Required to fill'); ?>" required>
                    <p class="help-block" style="color:#E80000;"></p>
                </div>
            </div>             
            <div class="control-group">
                <!-- Password-->
                <label class="control-label" for="password"><?= $this->t->translate('Password'); ?></label>
                <div class="controls">
                    <input type="password" class="form-control" id="password" name="password" minlength="6" data-validation-minlength-message="<?= $this->t->translate('Too short: Minimum of \'6\' characters'); ?>" data-validation-required-message="<?= $this->t->translate('Required to fill'); ?>" required>
                    <p class="help-block" style="color:#E80000;"></p>
                </div>
            </div>
            <div class="control-group">
            <!-- Password -->
                <label class="control-label"><?= $this->t->translate('Password (Confirm)'); ?></label>
                <div class="controls">
                    <input type="password" class="form-control" id="password_confirm" name="password_confirm" data-validation-match-match="password" data-validation-match-message="<?= $this->t->translate('The entered passwords do not match'); ?>" data-validation-required-message="<?= $this->t->translate('Required to fill'); ?>" required>
                    <p class="help-block" style="color:#E80000;"></p>
                </div>
            </div>
            <br>
            <div class="control-group">
               <div class="controls">
                   <button type="submit" class="btn btn-primary"><?= $this->t->translate('Save'); ?></button>
               </div>
           </div>
        </form><?php
$this->appendAfterBodyScript($this->basePath.'/js/jqBootstrapValidation.js');
$this->appendAfterBodyScript('$(function () { $("input").not("[type=submit]").jqBootstrapValidation(); } );', false);
$this->appendAfterBodyScript('$("input").focus(function(e) { $("div.message-info-alert").html(""); }); ', false);
$str = "   ". 
"$(document).ready(function(){
    function slideout(){
        setTimeout(function(){
            $(\".response-alert\").slideUp(\"slow\", function () {
        });
        }, 2000);
    }

    slideout();
})";
if(isset($this->isSave)) {
    $this->appendAfterBodyScript($str, false);  
}
?>