<?php

echo $this->getDoctype()."\n";?>
<html lang="$this->languages->getCurrentLanguage()">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="<?= $this->basePath ?>/images/favicon.ico">
<title><?= $this->t->translate('Sign in') ?></title>
<style>
body {background:#216594;font-family: Arial, Helvetica, sans-serif;}
a {color:#fff;text-decoration: underline;}
a:hover {color:#fff;text-decoration: none;}
.login_box {margin: 0 auto;margin-top: 100px;padding: 30px;width: 350px;background-color: #1D4E6F;background: -moz-linear-gradient(#06549E, #013669 60%, #062A4C);background: -webkit-linear-gradient(#06549E, #013669 60%, #062A4C);background: -o-linear-gradient(#06549E, #013669 60%, #062A4C);background: -ms-linear-gradient(#06549E, #013669 60%, #062A4C);background: linear-gradient(#06549E, #013669 60%, #062A4C);border-radius: 2px;box-shadow: 0px 1px 2px #111;}
.login_box h1 {text-align: center;font-size: 1.8em;color:#fff; margin: 0;}
.login_box input[type=submit] {width: 100%;display: block;margin:0 0 10px 0;}
.login_box input[type=text], input[type=password] {width: 334px;height: 40px;font-size: 16px; margin:0 0 10px 0;background: #fff;border: 1px solid #555;padding: 0 8px;}
.login_box input[type=text]:hover, input[type=password]:hover {-moz-box-shadow: inset 0 1px 2px #aaa;-webkit-box-shadow: inset 0 1px 2px #aaa;box-shadow: inset 0 1px 2px #aaa;}
.login_box .submit {border: 0px;color: #fff;font-size: 14px;background-color:#6291DC;padding: 16px 0px;}
.login_box .submit:hover {background-color:#406AAD;}
.login-help{font-size: 12px;}
#loading_bg{display: none;position: fixed;left: 0px;top: 0px;width: 100%;height: 100%;z-index: 9999;background:#292929;opacity: 0.7;}
#loading{display: none;position: fixed;left: 0px;top: 0px;width: 100%;height: 100%;z-index: 9999;}
#loading div {width: 100%; height: 100%;background:url(<?= $this->basePath ?>/images/ajax-indicator.gif) center center no-repeat;}
#error {display:none;margin: 0 0 5px 0;line-height:1.4;font-size: 14px;font-weight:bold; text-align: left;color: #FF9B00;}
</style>
</head>
<body>
    <div class="login_box">
        <h1><?= $this->t->translate('Sign in'); ?></h1><br>
        <div id="error"></div>
        <form id="login-form" method="POST">
            <input type="text" name="username" placeholder="<?= $this->t->translate('Username'); ?>">
            <input type="password" name="password" placeholder="<?= $this->t->translate('Password'); ?>">
            <input type="submit" name="login" class="submit" value="<?= $this->t->translate('Login'); ?>">
        </form>
        <div class="login-help">
            <a href="<?= $this->router->createPath('account_forgot_password'); ?>"><?= $this->t->translate('Forgot Password'); ?>?</a>
        </div>
    </div>
    
    <div id="loading_bg"></div>
    <div id="loading"><div></div></div>
    
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>-->
<script src="<?= $this->basePath ?>/js/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $(document).ajaxStart(function () {
            $('#loading_bg').fadeIn(300);
            $('#loading').fadeIn(300);
            $('body').css('cursor', 'wait');
        });
        $(document).ajaxStop(function () {
            $('#loading_bg').fadeOut(300);
            $('#loading').fadeOut(300);
            $('body').css('cursor', 'default');
        });
         
        $("#login-form").on('submit', function(){
            if ( this.username.value == "" || this.password.value == "") {
                $("div#error").css('display','block');
                $("div#error").html("<?= $this->t->translate('Please, enter valid username and password'); ?>");
                return false;
            }
            $.post( '<?= $this->router->createPath('account_login'); ?>', $("#login-form :input").serializeArray(), function(data) {
                if(data.error) {
                    $("div#error").css('display','block');
                    $("div#error").html(data.message);
                    $("#login-form").trigger( 'reset' );
                    return false;
                } else {
                    document.location.href = "<?= $this->router->createPath('index'); ?>";
                }
            });
            
            return false;
        });
        
        $("#login-form :input").on('click',function(){
            $("div#error").css('display','none');
        });
    });
</script>
</body>
</html>