<?php

?><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Confirmation</title>
<body style="background: #fff;">
    <h3><?= $this->displayName; ?>, You have requested a new password since forgotten old.</h3>
    <p>Set your new password below. To activate it, go to this link:</p>
    <p><a href="<?= $this->url;?>" style="color: #204d74;"><?= $this->url;?></a></p>
    <p>login: <b><?=$this->username; ?></b></p>
    <p>password: <b><?=$this->password; ?></b></p>
    <br>
    <br>
    <p>If you did not request a new password, please ignore this message and your password will stay unchanged.</p>
    <p>Regards, Administrator.<p>    
</body>
</html>