<!DOCTYPE HTML>
<html>
<head>
<title><?= $this->t->translate('Page not found') ?></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<style type="text/css">   
body{
    font-family: Arial, Helvetica, sans-serif;
    background:#216594;
}
.logo{
    margin-top:50px;
}	
.logo h1{
    font-size:200px;
    color:#E2F138;
    text-align:center;
    margin-bottom:1px;
    text-shadow:1px 1px 6px #333;
}	
.logo p{
    color:#fff;
    font-size:20px;
    margin-top:1px;
    text-align:center;
}
.back a{
    color:#fff;
    background:#08285D;
    text-decoration:none;
    padding:8px 100px;
    font-size:14px;
    font-weight:bold;
    -webkit-border-radius:3em;
    -moz-border-radius:.3em;
    -border-radius:.3em;
}		
</style>
</head>
<body>
    <div class="wrap">
        <div class="logo">
            <h1>404</h1>
            <p><?= $this->t->translate('Error occured! - Page not found') ?></p>
            <div class="back">
                <p><a href="<?= $this->siteUrl ?>"><?= $this->t->translate('Back') ?></a></p>
            </div>
        </div>
    </div>	
</body>