<?php
$title = $this->getTitle();
if($title) {
    $this->setTitle($title." :: ".$this->t->translate('Create new account'));
} else {
    $this->setTitle($this->t->translate('Create new account'));
}
?><div class="row">
            <div class="col-lg-12">
                <br>
                <ol class="breadcrumb text-capitalize">
                    <li><a href="<?= $this->router->createPath('index'); ?>"><?= $this->t->translate('Home'); ?></a></li>
                    <li><a class="text-lowercase" href="<?= $this->router->createPath('users_list'); ?>"><?= $this->t->translate('User list'); ?></a></li>
                    <li class="active text-lowercase"><?= $this->t->translate('Create new account'); ?></li>
                </ol>
            </div>
        </div>
        <div class="page-header">
            <h2><?= $this->t->translate('Create new account'); ?></h2>
        </div>
<?php if(isset($this->showAlert)): ?>
        <div class="message-info-alert">
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Error:</span>
                <?= $this->t->translate($this->showAlert);?>
            </div>
        </div>
<?php endif; ?>
        <form id="create-user-form" role="form" action="<?= $this->router->createPath('users_add'); ?>" method="POST" novalidate>
            <div class="control-group">
                <!-- Username -->
                <label class="control-label" for="username"><?= $this->t->translate('Username'); ?></label>
                <div class="controls">
                    <input type="text" class="form-control" id="username" name="username" maxlength="255" data-validation-maxlength-message="<?= $this->t->translate('Too long: Maximum of \'255\' characters'); ?>" minlength="4" data-validation-minlength-message="<?= $this->t->translate('Too short: Minimum of \'4\' characters'); ?>" data-validation-regex-regex="[a-zA-Z][a-zA-Z0-9]*" data-validation-regex-message="<?= $this->t->translate('It may contain the letter [a-z] [A-Z], the numbers [0-9] and start only with the letter'); ?>" data-validation-ajax-ajax="<?= $this->router->createPath('users_check_username', ['user_id'=>0]); ?>" data-validation-required-message="<?= $this->t->translate('Required to fill'); ?>" required>
                    <p class="help-block" style="color:#E80000;"></p>
                </div>
            </div>
            <div class="control-group">
                <!-- E-mail -->
                <label class="control-label" for="email"><?= $this->t->translate('E-mail'); ?></label>
                <div class="controls">
                    <input type="email" class="form-control" id="email" name="email" maxlength="255" data-validation-maxlength-message="<?= $this->t->translate('Too long: Maximum of \'255\' characters'); ?>" data-validation-email-message="<?= $this->t->translate('Invalid e-mail address'); ?>" data-validation-ajax-ajax="<?= $this->router->createPath('users_check_email', ['user_id'=>0]); ?>" data-validation-required-message="<?= $this->t->translate('Required to fill'); ?>" required>
                    <p class="help-block" style="color:#E80000;"></p>
                </div>
            </div>            
            <div class="control-group">
                <!-- Display name -->
                <label class="control-label" for="display_name"><?= $this->t->translate('Display Name'); ?></label>
                <div class="controls">
                    <input type="text" class="form-control" id="display_name" name="display_name" maxlength="50" data-validation-maxlength-message="<?= $this->t->translate('Too long: Maximum of \'50\' characters'); ?>" minlength="4" data-validation-minlength-message="<?= $this->t->translate('Too short: Minimum of \'4\' characters'); ?>" data-validation-required-message="<?= $this->t->translate('Required to fill'); ?>" required>
                    <p class="help-block" style="color:#E80000;"></p>
                </div>
            </div>
            <div class="control-group">
                <!-- Password-->
                <label class="control-label" for="password"><?= $this->t->translate('Password'); ?></label>
                <div class="controls">
                    <input type="password" class="form-control" id="password" name="password" minlength="6" data-validation-minlength-message="<?= $this->t->translate('Too short: Minimum of \'6\' characters'); ?>" data-validation-required-message="<?= $this->t->translate('Required to fill'); ?>" required>
                    <p class="help-block" style="color:#E80000;"></p>
                </div>
            </div>
            <div class="control-group">
            <!-- Password -->
                <label class="control-label"><?= $this->t->translate('Password (Confirm)'); ?></label>
                <div class="controls">
                    <input type="password" class="form-control" id="password_confirm" name="password_confirm" data-validation-match-match="password" data-validation-match-message="<?= $this->t->translate('The entered passwords do not match'); ?>" data-validation-required-message="<?= $this->t->translate('Required to fill'); ?>" required>
                    <p class="help-block" style="color:#E80000;"></p>
                </div>
            </div>
            <div class="control-group alert alert-info">
                <label class="control-label"><?= $this->t->translate('Role'); ?>:</label>
                <div class="controls">
                    <select id="role" name="role" class="form-control">
<?php foreach ($this->roles as $key=>$name): ?>
                    <option value="<?= $key ?>"><?= $name ?></option>
<?php endforeach;?>                        
                    </select>
                </div>
            </div>
            <div class="control-group">
               <div class="controls">
                   <button type="submit" class="btn btn-primary"><?= $this->t->translate("Create"); ?></button>
               </div>
           </div>
        </form><?php
$this->appendAfterBodyScript($this->basePath.'/js/jqBootstrapValidation.js');
$this->appendAfterBodyScript('$(function () { $("input").not("[type=submit]").jqBootstrapValidation(); } );', false);
$this->appendAfterBodyScript('$("input").focus(function(e) { $("div.message-info-alert").html(""); }); ', false);
?>