<?php
$title = $this->getTitle();
if($title) {
    $this->setTitle($title." :: ".$this->t->translate('Delete user'));
} else {
    $this->setTitle($this->t->translate('Delete user'));
}
?><div class="row">
            <div class="col-lg-12">
                <br>
                <ol class="breadcrumb text-capitalize">
                    <li><a href="<?= $this->router->createPath('index'); ?>"><?= $this->t->translate('home'); ?></a></li>
                    <li><a class="text-lowercase" href="<?= $this->router->createPath('users_list'); ?>"><?= $this->t->translate('User list'); ?></a></li>
                    <li class="active text-lowercase"><?= $this->t->translate('Delete user') ?></li>
                </ol>
            </div>
        </div>
        <br>
        <h2><?= $this->t->translate('Delete user'); ?> <span class="text-primary">"<?= $this->user->getDisplayName(); ?>"</span> ?</h2>
        <br>
        <form action="<?= $this->router->createPath('users_delete', ['user_id'=>$this->user->getId()]); ?>" method="post">
            <div>
                <button type="submit" class="btn btn-danger" name="del" value="true"><?= $this->t->translate('Yes'); ?></button>
                <button type="submit" class="btn btn-primary" name="del" value="false"><?= $this->t->translate('No'); ?></button>
            </div>
        </form>